### PR TITLE
Add workflow

### PR DESCRIPTION
**Pull request by ernilambar**
This will automate fetching of parser from WP.org.

### CODE REVIEW

**Comment by ernilambar** [comment]
cc: @swissspidy I have used workflow of regenerating readme and modified here to update parser class. It would be great if could review once and give feedback to optimize it.

**Comment by afragen** [comment]
This is wonderful. Awaiting feedback from @swissspidy

**Comment by swissspidy** [comment]
If it works it works :) I don't know why I'd need to review this one but looks good at first glance 👍

**Comment by afragen** [comment]
Thanks @swissspidy

**Pull request merged**
